version = 0.1
[default.deploy.parameters]
stack_name = "sam-img-s3"
s3_bucket= "nodejs-learning"
s3_prefix = "sam-img-s3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
